require "configs.impatient"
require "configs.cmp"
require "configs.lsp"
require "configs.autopairs"
require "configs.bufferline"
require "configs.bookmark"
require "configs.colorizer"

require "configs.blanklines"
require "configs.comment"
require "configs.copilot"
require "configs.git-blame"
require "configs.gitsigns"
require "configs.lualine"
require "configs.treesitter"
require "configs.telescope"
