require("configs.autopairs")
-- require("configs.colorizer")
require("configs.comment")
-- require("configs.gitsigns")
-- require("configs.indent_blankline")
require("configs.lsp_file").init()
-- require("configs.lualine")
require("configs.misc")
require("configs.nvim-tree")
require("configs.spectre")
require("configs.telescope")
require("configs.treesitter")
require("configs.visuals").init()

require("nvim-tree").setup()
